all:BFS DFS GBFS IDS UCS AStart

BFS:
	g++ -g -Wall BFS.cpp -o BFS
DFS:
	g++ -g -Wall DFS.cpp -o DFS
GBFS:
	g++ -g -Wall GBFS.cpp -o GBFS
IDS:
	g++ -g -Wall IDS.cpp -o IDS
UCS:
	g++ -g -Wall UCS.cpp -o UCS
AStart:
	g++ -g -Wall AStart.cpp -o AStart
run:
	./BFS
	./DFS
	./UCS
	./IDS
	./GBFS
	./AStart
clean:
	rm BFS DFS GBFS IDS UCS AStart
